apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydockerakscontainer-deployment
  labels:
    app: mybasicwebapp
spec:
  replicas: 1
  template:
    metadata:
      name: mydockerakscontainer
      labels:
        app: mybasicwebapp
    spec:
      containers:
      - name: mydockerakscontainer
        image: mybasicwebapp
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: mybasicwebapp

---

apiVersion: v1
kind: Service
metadata:
  name: mydockerakscontainer-service
spec:
  selector:
    app: mybasicwebapp
  ports:
    - port: 80
  type: LoadBalancer