apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybasicwebapp-deployment
  labels:
    app: mybasicwebapp
spec:
  replicas: 1
  template:
    metadata:
      name: mybasicwebapp
      labels:
        app: mybasicwebapp
    spec:
      containers:
      - name: mydockerakscontainer13580
        image: mybasicwebapp
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: mybasicwebapp

---

apiVersion: v1
kind: Service
metadata:
  name: mybasicwebapp-service
spec:
  selector:
    app: mybasicwebapp
  ports:
    - port: 80
  type: LoadBalancer