# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mybasicwebapp:
    image: mybasicwebapp
    build:
      context: .
      dockerfile: MyDockerAKSBasicWebApp/MyBasicWebApp/Dockerfile
    ports:
      - 5180:5180
